### ISSUE TITLE
Local copy of federated users 

### ISSUE THREAD

**Issue by Novelz** [opensingular/singular-keycloak-database-federation#1]
Hi there!
I was able to implement your federation SPI and everything went fine connecting to a remote MySql instance and retrieving the users stored there.
I've only one question, are the users supposed to be copied locally in the Keycloak database? I've replaced the H2 default database with a Mysql one and I can see the users in the FEDERATED_USER table, but when I try to login I keep getting "user not found error".

Is there something I'm missing with the authentication?

**Comment by viniciusuriel** [comment]
Hi @Novelz , there is no need to copy anything into the internal keycloak database be it h2 or any other RDMS.
As far as I understand it, the FEDERATED_USER table is populated by keycloak as needed.

I just tested an SPI configuration to a remote database, but now, using a PostgreSQL as keycloak database instead of the default h2 configuration and everything went fine.

Try to hit the "Remove Imported" and "Unlink Users" at the bottom of the federation provider configuration page and change cache policy to "NO_CACHE". 

If still no luck:

- keep in mind that the returned "id" column is stored as text on the keycloak tables. You might need to cast the value parameter in the  "Find user by id SQL query" SQL.
- Check for a more detailed message in the log file, if possible, attach it here.

Best regards,
