### ISSUE TITLE
Keycloak 17 Support

### ISSUE THREAD

**Issue by wcoc** [opensingular/singular-keycloak-database-federation#11]
Hello, looks like the module is not working in the new release of Keycloak due to the change the way de deployment is done.

Is there a plan to refactor it and make if works?

**Comment by viniciusuriel** [comment]
Sure, I will refactor the maven packaging so that it can be deployed in a Quarkus based keycloak.

In fact I have already deployd it in a keycloak 17 Quarkus based installation, but manually.

To do so you could just build this project and deploy the .jars instead of deploying the .ear:

$mvn clean package install
\# Copy every jar on singular-keycloak-database-federation\ear-module\target\singular-user-storage-provider-bundle-1.5 to "\<keycloak\>/providers" directory under your keycloak installation.
\# Before restarting keycloak  run:
$kc.sh build

For more information see https://www.keycloak.org/docs/latest/server_development/#packaging-and-deployment

I hope it helps while I am not done with this packaging refactoring.
If you try it and face any issue, let me know for further helping.

**Comment by viniciusuriel** [comment]
> Hello, looks like the module is not working in the new release of Keycloak due to the change the way de deployment is done.
> 
> Is there a plan to refactor it and make if works?

To deploy it using instructions in my previous comment it would be necessary to do some tweaks.

I ended up finishing the actual migration to keycloak 17+.

You can download and test it under tag 2.0.

**Comment by wcoc** [comment]
That's awesome. Thank you so much.
