### ISSUE TITLE
Where is the .ear file for installation?

### ISSUE THREAD

**Issue by aspiazza** [opensingular/singular-keycloak-database-federation#3]
I am having trouble finding out how to install this in KeyCloak. Am I missing something from the doumentation?

**Comment by viniciusuriel** [comment]
If you are using a default keycloak setup, you just need to copy the `.ear` file to the folder  <keycloak_dir>/standalone/deployments

**Comment by aspiazza** [comment]
> If you are using a default keycloak setup, you just need to copy the `.ear` file to the folder <keycloak_dir>/standalone/deployments

Great, thanks for the quick reply. Where is this .ear file? I see the ear-module has a pom.xml file in it?

**Comment by viniciusuriel** [comment]
Did you build the project with maven? If so, you will find a .ear file in the ear-module/target folder.

**Comment by aspiazza** [comment]
Hm, where should I run the build command from? The deployments folder?

**Comment by viniciusuriel** [comment]
@aspiazza , this repository is an open source java maven project meant to
be compiled  and then deployed in keycloak. The way you write your
questions makes me think that you are unaware of what is maven or how to
build a java project.  If this is the case, there is no problem, you can
still benefit from this federation provider, but I think it is better you
look for some help on your organization before.

After building it with maven, like I described in the README file, and then
deploying it to the corresponding folder, the one I have previously
indicated, you should see an option to select the singular-db-user-provider
on the web interface of keycloak.

This is not a default pre-configured solution, keep in mind that even after
everything is deployed, you still have to write your SQL queries
accordingly so that the provider can look up your users and check passwords
against the database.

Feel free to ask any other questions, I will try to help somehow.

Best regards,
